server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.springbootdemo.domain

#打印sql语句
logging:
  level:
    com.springboot.mybatis.dao : debug

#pagehelper分页插件配置
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  .params=count: countSql



