server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.springbootdemo.domain






